# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NITRIX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NITRIX
	pod 'SnapKit', '~> 5.0.0'
	pod 'Alamofire'
	pod 'RxSwift', '6.5.0'
    	pod 'RxCocoa', '6.5.0'
  target 'NITRIXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NITRIXUITests' do
    # Pods for testing
  end

end
